# ---
# title: Auto Assign PR
# description: Automatically add pull request reviewers and assignees to streamline pull request triage and reviews.
# tags:
#   - automation
#   - pr
#   - review
# icon: person_add
# owner: ghwfxlab
# ---
---
name: auto-assign-pr
files:
  - source: auto-assign-pr.yaml
    target: .github/workflows/auto-assign-pr.yaml
  - source: config/auto_assign.yaml
    target: .github/auto_assign.yaml
