---
name: Lint Code Base

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      statuses: write
      pull-requests: write
      packages: read
    steps:
      - name: Checkout The Source Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Load Super-Linter configuration
        run: |
          echo "Loading Super-Linter configuration from .github/super-linter.env"
          grep -v '^#' .github/super-linter.env >> "$GITHUB_ENV"

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pre-commit:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout The Source Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run Pre-commit Hooks
        run: |
          export SKIP="textlint,super-linter-fix"
          pre-commit run --all-files
